# Generated by Django 5.2 on 2025-04-21 20:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastaImagens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pasta_nome",
                    models.CharField(
                        help_text="Este nome será convertido para CAIXA ALTA e sem caracteres especiais",
                        max_length=100,
                        verbose_name="Nome da Pasta",
                    ),
                ),
                (
                    "arquivos_zip",
                    models.FileField(
                        help_text="Apenas arquivos ZIP contendo imagens (JPEG, PNG, RAW, etc.)",
                        storage=django.core.files.storage.FileSystemStorage(
                            location="static/"
                        ),
                        upload_to="temp_zip/",
                        verbose_name="Arquivo ZIP com Imagens",
                    ),
                ),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pasta de Imagens",
                "verbose_name_plural": "Pastas de Imagens",
            },
        ),
    ]
