# Generated by Django 5.2 on 2025-04-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_pastaimagens"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZipDeFotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("arquivo_zip", models.FileField(upload_to="temp_zip/")),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="PastaImagens",
        ),
    ]
