# Generated by Django 5.2 on 2025-04-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_zipdefotos_delete_pastaimagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkGaleriaFake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📁 Galeria de Fotos',
                'verbose_name_plural': 'Acessar Galeria',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='zipdefotos',
            options={'verbose_name': '📦 Enviar fotos (.zip)', 'verbose_name_plural': '📦 Enviar fotos (.zip)'},
        ),
        migrations.AlterField(
            model_name='zipdefotos',
            name='nome',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
